import React from 'react';
import PropTypes from 'prop-types';
import classNames from 'classnames';

import css from './TermsOfService.module.css';

const TermsOfService = props => {
  const { rootClassName, className } = props;
  const classes = classNames(rootClassName || css.root, className);

  // prettier-ignore
  return (
    <div className={classes}>
      <p className={css.lastUpdated}>Last updated: July 22, 2021</p>

  <p>Please read these Terms of Service carefully as they contain important information about your legal rights, remedies and obligations. By accessing or using the Caf&eacute; Temps Platform, you agree to comply with and be bound by these Terms of Service.</p>
  <p>Please note: Section 19 of these Terms of Service contains an arbitration clause and class action waiver that applies to all Caf&eacute; Temps Members. If you reside in the United States, this provision applies to all disputes with Caf&eacute; Temps. If you reside outside of the United States, this provision applies to any action you bring against Caf&eacute; Temps in the United States. It affects how disputes with Caf&eacute; Temps are resolved. By accepting these Terms of Service, you agree to be bound by this arbitration clause and class action waiver. Please read it carefully.</p>
  <p>Thanks for using Caf&eacute; Temps!</p>
  <p>These Terms of Service ("Terms") constitute a legally binding agreement ("Agreement") between you and Caf&eacute; Temps (as defined below) governing your access to and use of the Caf&eacute; Temps website, including any subdomains thereof, and any other websites owned or operated by Caf&eacute; Temps (collectively, "Site") and all associated services (collectively, "Caf&eacute; Temps Services"). The Site and Caf&eacute; Temps Services together are hereinafter collectively referred to as the &ldquo;Caf&eacute; Temps Platform&rdquo;. Our other policies applicable to your use of the Caf&eacute; Temps Platform are incorporated by reference into this Agreement.</p>
  <p>When these Terms mention &ldquo;Caf&eacute; Temps,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our,&rdquo; it refers to Cafe Temps, LLC.</p>
  <p>Our collection and use of personal information in connection with your access to and use of the Caf&eacute; Temps Platform is described in our Privacy Policy.</p>
  <h2>Table of Contents</h2>
  <ol>
  <li >Scope of Caf&eacute; Temps Services</li>
  <li >Eligibility, Using the Caf&eacute; Temps Platform, Member Verification</li>
  <li >Modification of these Terms</li>
  <li >Account Registration</li>
  <li >Content</li>
  <li >No Contractual Relationship and No Booking Transaction Service Fees</li>
  <li >Terms specific for Studios</li>
  <li >Terms specific for Artists</li>
  <li >Booking Modifications, Cancellations and Refunds, Resolution Center</li>
  <li >Ratings and Reviews</li>
  <li >Damage to Studios, Disputes between Members</li>
  <li >Taxes</li>
  <li >Prohibited Activities</li>
  <li >Term and Termination, Suspension and other Measures</li>
  <li >Disclaimers</li>
  <li >Liability</li>
  <li >Indemnification</li>
  <li >Dispute Resolution</li>
  <li >Feedback</li>
  <li >Applicable Law and Jurisdiction</li>
  <li >General Provisions</li>
  </ol>
  <h3>1. Scope of Caf&eacute; Temps Services and Interaction with other Members</h3>
  <p>1.1 Our Services provide a platform for restaurant managers to search and hire local workers to help staff restaurant locations. Caf&eacute; Temps has no liability with respect to any communications, transactions, interactions, disputes or any relations whatsoever between you and any other member, person or organization. You are solely responsible for your interactions with other members of our Services. We reserve the right, but have no obligation, to monitor interactions between the members of our platform.</p>
  <p>Remember, Caf&eacute; Temps is just a platform that enables members to communicate and interact with others in the restaurant industry. We cannot be responsible for the interactions that you have with other Caf&eacute; Temps members, so please use good judgment and keep safety in mind when you use our Services.</p>
  <p>1.2 The Caf&eacute; Temps Platform is an online marketplace that enables registered users (&ldquo;Members&rdquo;) to publish such Worker profiles on the Caf&eacute; Temps Platform (&ldquo;Listings&rdquo;) and to communicate and transact directly with Members that are seeking to hire workers through hourly contracts.&nbsp;</p>
  <p>1.3 As the provider of the Caf&eacute; Temps Platform, Caf&eacute; Temps does not own, create, sell, resell, provide, control, manage, offer, deliver, or supply any Listings or Services. Members alone are responsible for their Listings and services provided. When Members make or accept a booking, they are entering into a non-binding agreement directly with each other. Caf&eacute; Temps is not and does not become a party to or other participant in any contractual relationship between Members, nor is Caf&eacute; Temps an insurer.</p>
  <p>1.4 While we may (at our own discretion) help facilitate the resolution of disputes, Caf&eacute; Temps has no control over and does not guarantee (i) the existence, quality, safety, or suitability of any listings on the platform, (ii) the truth or accuracy of any Listing descriptions, Ratings, Reviews, or other Member Content (as defined below), or (iii) the performance or conduct of any Member or third party. Caf&eacute; Temps does not endorse any Member or Listing. Any references to a Member being "verified" (or similar language) only indicate that the Member has completed a relevant verification process and nothing else. Any such description is not an endorsement, certification or guarantee by Caf&eacute; Temps about any Member, including of the Member's identity or background or whether the Member is trustworthy, safe or suitable. You should always exercise due diligence and care when deciding whether to book a Worker, accept a booking request from a Restaurant, or communicate and interact with other Members, whether online or in person. Verified Reviews are intended only to indicate Member feedback from past bookings, and are therefore not an endorsement by Caf&eacute; Temps of any Listing.</p>
  <p>1.5 Caf&eacute; Temps is primarily a marketplace platform, therefore if you List your services as a Worker, you are not an employee, agent, joint venturer or partner of Caf&eacute; Temps for any reason, and you act exclusively on your own behalf and for your own benefit, and not on behalf, or for the benefit, of Caf&eacute; Temps.</p>
  <p>1.6 To promote the Caf&eacute; Temps Marketplace and to increase the exposure of Listings to potential customers (Restaurants),&nbsp; Listings and other Member Content (as defined below) may be displayed on other websites, in applications, within emails, and in online and offline advertisements.</p>
  <p>1.7 The Caf&eacute; Temps Platform may contain links to third-party websites or resources (&ldquo;Third-Party Services&rdquo;). Such Third-Party Services may be subject to different terms and conditions and privacy practices. Caf&eacute; Temps is not responsible or liable for the availability or accuracy of such Third-Party Services, or the content, products, or services available from such Third-Party Services. Links to such Third-Party Services are not an endorsement by Caf&eacute; Temps of such Third-Party Services.</p>
  <p>1.8 Due to the nature of the Internet, Caf&eacute; Temps cannot guarantee the continuous and uninterrupted availability and accessibility of the Caf&eacute; Temps Platform. Caf&eacute; Temps may restrict the availability of the Caf&eacute; Temps Platform or certain areas or features thereof, if this is necessary in view of capacity limits, the security or integrity of our servers, or to carry out maintenance measures that ensure the proper or improved functioning of the Caf&eacute; Temps Platform. Caf&eacute; Temps may improve, enhance and modify the Caf&eacute; Temps Platform and introduce new Caf&eacute; Temps Services from time to time.</p>
  <h3>2. Eligibility, Using the Caf&eacute; Temps Platform, Member Verification</h3>
  <p>2.1 You must be at least 16 years old and able to enter into legally binding contracts to access and use the Caf&eacute; Temps Platform or register an Caf&eacute; Temps Account. By accessing or using the Caf&eacute; Temps Platform you represent and warrant that you are 16 or older and have the legal capacity and authority to enter into a contract.</p>
  <p>2.2 Caf&eacute; Temps may make the access to and use of the Caf&eacute; Temps Platform, or certain areas or features of the Caf&eacute; Temps Platform, subject to certain conditions or requirements, such as completing a verification process, meeting specific quality or eligibility criteria, meeting Ratings or Reviews thresholds, or booking and cancellation history.</p>
  <p>2.3 User verification on the Internet is difficult and we do not assume any responsibility for the confirmation of any Member&rsquo;s identity. Notwithstanding the above, for transparency and fraud prevention purposes, and as permitted by applicable laws, we may, but have no obligation to (i) ask Members to provide a form of government identification or other information or undertake additional checks designed to help verify the identities or backgrounds of Members.</p>
  <p>2.4 The access to or use of certain areas and features of the Caf&eacute; Temps Platform may be subject to separate policies, standards or guidelines, or may require that you accept additional terms and conditions. If there is a conflict between these Terms and terms and conditions applicable to a specific area or feature of the Caf&eacute; Temps Platform, the latter terms and conditions will take precedence with respect to your access to or use of that area or feature, unless specified otherwise. Such additional terms and these Terms are referred to herein as the &ldquo;Agreement.&rdquo;</p>
  <h3>3. Modification of these Terms</h3>
  <p>PLEASE NOTE THAT THE AGREEMENT IS SUBJECT TO CHANGE BY Caf&eacute; Temps IN ITS SOLE DISCRETION AT ANY TIME. IF WE MAKE CHANGES TO THESE TERMS, WE WILL POST THE REVISED TERMS ON THE Caf&eacute; Temps PLATFORM AND UPDATE THE &ldquo;LAST UPDATED&rdquo; DATE AT THE TOP OF THESE TERMS. IF WE MAKE ANY MATERIAL CHANGES THAT AFFECT YOUR USE OF THE Caf&eacute; Temps SERVICES, AND YOU HAVE REGISTERED WITH US TO CREATE A Caf&eacute; Temps ACCOUNT, WE WILL ALSO ENDEAVOR TO SEND AN E-MAIL TO YOU AT THE LAST E-MAIL ADDRESS YOU PROVIDED TO US PURSUANT TO THE AGREEMENT. ANY CHANGES TO THE AGREEMENT WILL BE EFFECTIVE IMMEDIATELY FOR NEW USERS OF THE SITE AND/OR Caf&eacute; Temps SERVICES AND WILL BE EFFECTIVE ON THE EFFECTIVE DATE PROVIDED ON THE APPLICABLE NOTICE OF SUCH CHANGES FOR EXISTING MEMBERS. WE MAY REQUIRE YOU TO PROVIDE CONSENT TO THE UPDATED AGREEMENT IN A SPECIFIED MANNER BEFORE FURTHER USE OF THE SITE AND/OR THE Caf&eacute; Temps SERVICES IS PERMITTED. IF YOU DO NOT AGREE TO ANY CHANGE(S) AFTER RECEIVING A NOTICE OF SUCH CHANGE(S), YOU SHALL STOP USING THE SITE AND/OR THE Caf&eacute; Temps SERVICES. OTHERWISE, YOUR CONTINUED USE OF THE SITE AND/OR Caf&eacute; Temps SERVICES CONSTITUTES YOUR ACCEPTANCE OF SUCH CHANGE(S). PLEASE REGULARLY CHECK THE SITE TO VIEW THE THEN-CURRENT TERMS.</p>
  <h3>4. Account Registration</h3>
  <p>4.1 You must register an account ("Caf&eacute; Temps Account") to access and use certain features of the Caf&eacute; Temps Platform, such as publishing or booking a Listing. If you are registering a Caf&eacute; Temps Account for a company or other legal entity, you represent and warrant that you have the authority to legally bind that entity and grant us all permissions and licenses provided in these Terms.</p>
  <p>4.2 You can register a Caf&eacute; Temps Account by using a valid email address and creating a password.</p>
  <p>4.3 You must provide accurate, current and complete information during the registration process and keep your Caf&eacute; Temps Account and public Caf&eacute; Temps Account profile page information up-to-date at all times. If you provide any information that is untrue, inaccurate, not current or incomplete, or we have reasonable grounds to suspect that any information you provide is untrue, inaccurate, not current or incomplete, we have the right to suspend or terminate your Caf&eacute; Temps Account and refuse any and all current or future use of Caf&eacute; Temps Platform (or any portion thereof). You agree not to create a Caf&eacute; Temps Account using a false identity or information, or on behalf of someone other than yourself.</p>
  <p>4.4 You may not register more than one (1) Caf&eacute; Temps Account unless Caf&eacute; Temps authorizes you to do so. You may not assign or otherwise transfer your Caf&eacute; Temps Account to another party.</p>
  <p>4.5 You are responsible for maintaining the confidentiality and security of your Caf&eacute; Temps Account credentials and may not disclose your credentials to any third party. You may not share your Caf&eacute; Temps Account or password with anyone, and you agree to (y) notify Caf&eacute; Temps immediately of any unauthorized use of your password or any other breach of security; and (z) exit from your Caf&eacute; Temps Account at the end of each session. You must immediately notify Caf&eacute; Temps if you know or have any reason to suspect that your credentials have been lost, stolen, misappropriated, or otherwise compromised or in case of any actual or suspected unauthorized use of your Caf&eacute; Temps Account. You are liable for any and all activities conducted through your Caf&eacute; Temps Account. You agree that you shall monitor your Caf&eacute; Temps Account to restrict use by minors, and you will accept full responsibility for any unauthorized use of Caf&eacute; Temps Platform by minors.</p>
  <h3>5. Content</h3>
  <p>5.1 Caf&eacute; Temps may, at its sole discretion, enable Members to (i) create, upload, post, send, receive and store content, such as text, photos, audio, video, or other materials and information on or through the Caf&eacute; Temps Platform ("Member Content"); and (ii) access and view Member Content and any content that Caf&eacute; Temps itself makes available on or through the Caf&eacute; Temps Platform, including proprietary Caf&eacute; Temps content and any content licensed or authorized for use by or through Caf&eacute; Temps from a third party ("Caf&eacute; Temps Content" and together with Member Content, "Collective Content"). You acknowledge that all Collective Content is the sole responsibility of the party from whom such Collective Content originated. This means that you, and not Caf&eacute; Temps, are entirely responsible for all Member Content that you upload, post, e-mail, transmit or otherwise make available through the Caf&eacute; Temps Platform, and that you and other Members of the Caf&eacute; Temps Platform, and not Caf&eacute; Temps, are similarly responsible for all Member Content that you and they make available through the Caf&eacute; Temps Platform.</p>
  <p>5.2 The Caf&eacute; Temps Platform, Caf&eacute; Temps Content, and Member Content may in its entirety or in part be protected by copyright, trademark, and/or other laws of the United States and other countries. You acknowledge and agree that the Caf&eacute; Temps Platform and Caf&eacute; Temps Content, including all associated intellectual property rights, are the exclusive property of Caf&eacute; Temps and/or its licensors or authorizing third-parties. You will not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Caf&eacute; Temps Platform, Caf&eacute; Temps Content or Member Content. All trademarks, service marks, logos, trade names, and any other source identifiers of Caf&eacute; Temps used on or in connection with the Caf&eacute; Temps Platform and Caf&eacute; Temps Content are trademarks or registered trademarks of Caf&eacute; Temps in the United States and abroad. Trademarks, service marks, logos, trade names and any other proprietary designations of third parties used on or in connection with the Caf&eacute; Temps Platform, Caf&eacute; Temps Content, and/or Collective Content are used for identification purposes only and may be the property of their respective owners.</p>
  <p>5.3 You will not use, copy, adapt, modify, prepare derivative works of, distribute, license, sell, transfer, publicly display, publicly perform, transmit, broadcast or otherwise exploit the Caf&eacute; Temps Platform or Collective Content, except to the extent you are the legal owner of certain Member Content or as expressly permitted in these Terms. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Caf&eacute; Temps or its licensors, except for the licenses and rights expressly granted in these Terms.</p>
  <p>5.4 Subject to your compliance with these Terms, during the Term, Caf&eacute; Temps grants you a limited, non-exclusive, non-sublicensable, revocable, non-transferable right and license to access and view any Collective Content made available on or through the Caf&eacute; Temps Platform and accessible to you, solely for your personal and non-commercial use.</p>
  <p>5.5 By creating, uploading, posting, sending, receiving, storing, or otherwise making available any Member Content on or through the Caf&eacute; Temps Platform, you grant to Caf&eacute; Temps a non-exclusive, worldwide, royalty-free, irrevocable, perpetual (or for the term of the protection), sub-licensable and transferable license to such Member Content to access, use, store, copy, modify, prepare derivative works of, distribute, publish, transmit, stream, broadcast, and otherwise exploit in any manner such Member Content to provide and/or promote the Caf&eacute; Temps Platform, in any media or platform. Unless you provide specific consent, Caf&eacute; Temps does not claim any ownership rights in any Member Content and nothing in these Terms will be deemed to restrict any rights that you may have to use or exploit your Member Content.</p>
  <p>5.6 You are solely responsible for all Member Content that you make available on or through the Caf&eacute; Temps Platform. Accordingly, you represent and warrant that: (i) you either are the sole and exclusive owner of all Member Content that you make available on or through the Caf&eacute; Temps Platform or you have all rights, licenses, consents and releases that are necessary to grant to Caf&eacute; Temps the rights in and to such Member Content, as contemplated under these Terms; and (ii) neither the Member Content nor your posting, uploading, publication, submission or transmittal of the Member Content or Caf&eacute; Temps's use of the Member Content (or any portion thereof) will infringe, misappropriate or violate a third party's patent, copyright, trademark, trade secret, moral rights or other proprietary or intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.</p>
  <p>5.7 You will not post, upload, publish, submit or transmit any Member Content that: (i) is fraudulent, false, misleading (directly or by omission or failure to update information) or deceptive; (ii) is defamatory, libelous, obscene, pornographic, vulgar or offensive; (iii) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (iv) is violent or threatening or promotes violence or actions that are threatening to any other person; (v) promotes illegal or harmful activities or substances; or (vi) violates Caf&eacute; Temps&rsquo;s Content Policy or any other Caf&eacute; Temps policy. Caf&eacute; Temps may, without prior notice, remove or disable access to any Member Content that Caf&eacute; Temps finds to be in violation of these Terms or Caf&eacute; Temps&rsquo;s then-current Policies or Standards, or otherwise may be harmful or objectionable to Caf&eacute; Temps, its Members, third parties, or property.</p>
  <p>5.8 No Obligation to Pre-Screen Content. You acknowledge that we have no obligation to pre-screen Collective Content (including, but not limited to, Member Content), although we reserve the right in our sole discretion to pre-screen, refuse or remove any Collective Content. By entering into this Agreement, you hereby provide your irrevocable consent to such monitoring. You acknowledge and agree that you have no expectation of privacy concerning the transmission of your Member Content, including without limitation chat, text, or voice communications. In the event that we pre-screen, refuse or remove any Member Content, you acknowledge that we will do so for our benefit, not yours. Without limiting the foregoing, we shall have the right to remove any Member Content that violates the Agreement or is otherwise objectionable.</p>
  <p>5.9 Storage. Unless expressly agreed to by us in writing elsewhere, we have no obligation to store any of your Member Content that you make available on the Caf&eacute; Temps Platform. We have no responsibility or liability for the deletion or accuracy of any Collective Content, including your Member Content; the failure to store, transmit or receive transmission of Collective Content; or the security, privacy, storage, or transmission of other communications originating with or involving use of Caf&eacute; Temps Platform. Certain Caf&eacute; Temps Services may enable you to specify the level at which such Caf&eacute; Temps Services restrict access to your Member Content. You are solely responsible for applying the appropriate level of access to your Member Content. If you do not choose, the system may default to its most permissive setting. You agree that we retain the right to create reasonable limits on our use and storage of the Collective Content, including your Member Content, such as limits on file size, storage space, processing capacity, and similar limits described on the Site and as otherwise determined by us in our sole discretion.</p>
  <p>5.10 Caf&eacute; Temps respects copyright law and expects its Members to do the same. If you believe that any content on the Caf&eacute; Temps Platform infringes copyrights you own, please notify us in accordance with our Copyright Policy.</p>
  <h3>6. No Contractual Relationship</h3>
  <p>6.1 Caf&eacute; Temps is not a party to, has no involvement or interest in, makes no representations or warranties as to, and has no responsibility or liability with respect to any communications, transactions, interactions, disputes or any relations whatsoever between you and any other member, person or organization.&nbsp;</p>
  <h3>7. Terms specific for Worker Lisints</h3>
  <h4>7.1 Terms applicable to all Listings</h4>
  <p>7.1.1 When creating a Listing through the Caf&eacute; Temps Platform you must (i) provide accurate information about your skills and background, and provide any other pertinent information requested by Caf&eacute; Temps. You are responsible for keeping your Listing information up-to-date at all times.</p>
  <p>7.1.2 You are solely responsible for setting an hourly rate (including any Taxes if applicable) for your Listing (&ldquo;Listing Price&rdquo;).</p>
  <p>7.1.3 Any terms and conditions included in your Listing must not conflict with this Agreement or the cancellation policy you have identified for your Listing.</p>
  <p>7.1.4 The placement and ranking of Listings in search results on the Caf&eacute; Temps Platform may vary and depend on a variety of factors, such as search parameters and preferences, skills, restaurant requirements, price, Reviews and Ratings, type of Service, and/or ease of booking.</p>
  <p>7.1.6 When you accept or have pre-approved a booking request by an Restaurant, you are entering into a non-binding agreement with the Artist. Caf&eacute; Temps is not a party to this agreement, we are solely a platform that helps Restaurants discover worker talent.</p>
  <p>7.1.7 Caf&eacute; Temps requires that Restaurants obtain appropriate insurance for their facilities. We recommend you review any respective insurance policy carefully, and in particular make sure that you are familiar with and understand any exclusions to, and any deductibles that may apply for, such insurance policy, including, but not limited to, whether or not your insurance policy will cover the actions or inactions of contract workers at your location. This information is provided for convenience only and should not be deemed advice or replace the advice of an insurance professional.</p>
  <h3>8. Terms specific for Restaurants</h3>
  <h4>8.1 Terms applicable to all bookings</h4>
  <p>8.1.1 Subject to meeting any requirements set by the Worker, you can book a Listing available on the Caf&eacute; Temps Platform by following the respective booking process. A "booking" is not a legally binding agreement between you and the Studio. All applicable fees disclosed in the booking process are fee parameters set by the Worker. With your booking request, you indicate an interest to pay the total fees for any booking requested in connection with your Caf&eacute; Temps Account.&nbsp;</p>
  <p>8.1.2 Upon receipt of a booking confirmation from Caf&eacute; Temps, an agreement may be formed between you and your Worker, subject to any additional terms and conditions of the Studio that apply, including in particular the applicable cancellation policy specified on the Caf&eacute; Temps website.&nbsp;</p>
  <h3>9. Booking Modifications, Cancellations and Refunds, Resolution</h3>
  <p>9.1 Members are responsible for any modifications to a booking that they make via the Caf&eacute; Temps Platform. Caf&eacute; Temps is not responsible for any modifications.</p>
  <h3>10. Ratings and Reviews</h3>
  <p>10.1 Within a certain timeframe after completing a booking, Members can leave a public review (&ldquo;Review&rdquo;) and submit a star rating (&ldquo;Rating&rdquo;) about each other. Any Ratings or Reviews reflect the opinion of individual Members and do not reflect the opinion of Caf&eacute; Temps.</p>
  <p>10.2 Ratings and Reviews by Members must be fair, truthful and factual and may not contain any offensive or defamatory language. Ratings and Reviews must comply with Caf&eacute; Temps&rsquo;s Content Policy and Extortion Policy.</p>
  <h3>11. Damage to Accommodations, Disputes between Members</h3>
  <p>11.1 Because Caf&eacute; Temps is merely a platform, in the event that you have a dispute with one or more members, to the fullest extent permitted by applicable law you release us (and our officers, directors, members, employees, agents and affiliates) from claims, demands and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such disputes. If you are a California resident, you waive California Civil Code 1542, which says: &ldquo;A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which if known by him must have materially affected his settlement with the debtor.&rdquo;</p>
  <h3>12. Fees and Taxes</h3>
  <p>12.1 When you use the Caf&eacute; Temps Services as a Worker, Caf&eacute; Temps may hold a portion of the proceeds of your payout as a platform fee. All fees paid by Worker to Caf&eacute; Temps under the Agreement shall be considered solely for the purpose of managing the marketplace and reimbursing Caf&eacute; Temps costs for processing financial transactions.&nbsp;</p>
  <p>As part of registration, members acting as Workers must provide Stripe (our third party payments provider) with a valid bank account, as a condition to signing up for the Caf&eacute; Temps Services.</p>
  <p>As part of registration, members acting as Restaurant Managers must provide credit card information. In this case, the Payment Provider agreement governs your use of the designated credit card or PayPal account, and you must refer to that agreement, not this Agreement, to determine your rights and liabilities. By providing Caf&eacute; Temps with your credit card number or PayPal account and associated payment information, you agree that Caf&eacute; Temps is authorized to immediately invoice your Caf&eacute; Temps Account for all fees and charges due and payable to Caf&eacute; Temps hereunder and that no additional notice or consent is required. You agree to immediately notify Caf&eacute; Temps of any change in your billing address or the credit card or PayPal account used for payment hereunder. Caf&eacute; Temps reserves the right at any time to change its prices and billing methods, either immediately upon posting on the Caf&eacute; Temps Platform or by e-mail delivery to you.</p>
  <p>12.2 Members acting as Restaurant Managers will be responsible for payment of the applicable fee for any Caf&eacute; Temps Services. Except as set forth in the Agreement, all fees for the Caf&eacute; Temps Services are non-refundable. No contract will exist between Studio and Caf&eacute; Temps for the paid Caf&eacute; Temps Services until Caf&eacute; Temps accepts your order by a confirmatory e-mail or other appropriate means of communication.</p>
  <p>12.3 Third Party Payments Provider. Caf&eacute; Temps uses Stripe, Inc. (&ldquo;Payment Processor&rdquo;) as the third party service provider for payment services (e.g., card acceptance, merchant settlement, and related services). Your use of the Caf&eacute; Temps Platform and the payment processing provided by the Payment Processor is subject to the Stripe Connected Account Agreement that includes the Stripe Services Agreement, as may be modified by the Payment Processor from time to time (collectively, the &ldquo;Payment Processor Agreement&rdquo;). As a condition of using the Payment Processor&rsquo;s payment processing, you must provide accurate and complete information, and you authorize us to share this information with the Payment Processor. All bank and credit card information is sent directly to and stored with the Payment Processor using its security protocols. Caf&eacute; Temps does not store your payment information on its systems and shall not have any responsibility for the safety or security of that information. Your use of the Payment Processor&rsquo;s payment processing is conditioned upon your compliance with the Payment Processor Agreement, and if the Payment Processor Agreement is terminated by the Payment Processor, you may not be able to use the Caf&eacute; Temps Platform, or you may have your Caf&eacute; Temps Account suspended or terminated. We may change or add other payment processing services at any time upon notice to you, which may be subject to additional terms or conditions.</p>
  <p>12.4 As a Worker you are solely responsible for determining your obligations to report and pay applicable income taxes ("Taxes"). Stripe will provide annual financial reporting to aid in tax filing in the form of 1099 reporting. Caf&eacute; Temps suggests that all income be accurately reported as independent contractor, as workers are not considered employees of Caf&eacute; Temps.&nbsp;</p>
  <h3>13. Prohibited Activities</h3>
  <p>13.1 You are solely responsible for compliance with any and all laws, rules, regulations, and tax obligations that may apply to your use of the Caf&eacute; Temps Platform. In connection with your use of the Caf&eacute; Temps Platform, you will not and will not assist or enable others to:</p>
  <ul>
  <li >breach or circumvent any applicable laws or regulations, agreements with third-parties, third-party rights, or this Agreement, and any policies or standards of Caf&eacute; Temps;</li>
  <li >use the Caf&eacute; Temps Platform or Collective Content for any commercial or other purposes that are not expressly permitted by this Agreement or in a manner that falsely implies Caf&eacute; Temps endorsement, partnership or otherwise misleads others as to your affiliation with Caf&eacute; Temps;</li>
  <li >copy, store or otherwise access or use any information, including personally identifiable information about any other Member, contained on the Caf&eacute; Temps Platform in any way that is inconsistent with Caf&eacute; Temps&rsquo;s Privacy Policy or this Agreement or that otherwise violates the privacy rights of Members or third parties;</li>
  <li >use the Caf&eacute; Temps Platform in connection with the distribution of unsolicited commercial messages ("spam"); offer any Services that you do not yourself own or have permission to make available as through the Caf&eacute; Temps Platform;</li>
  <li >unless Caf&eacute; Temps explicitly permits otherwise, book any Listing if you will not actually be using the Worker services yourself;</li>
  <li >contact another Member for any purpose other than asking a question related to a your own booking, Listing, or the Member's use of the Caf&eacute; Temps Platform, including, but not limited to, recruiting or otherwise soliciting any Member to join third-party services, applications or websites, without our prior written approval;</li>
  <li >discriminate against or harass anyone on the basis of race, national origin, religion, gender, gender identity, physical or mental disability, medical condition, marital status, age or sexual orientation, or otherwise engage in any abusive or disruptive behavior;</li>
  <li >use, display, mirror or frame the Caf&eacute; Temps Platform or Collective Content, or any individual element within the Caf&eacute; Temps Platform, Caf&eacute; Temps's name, any Caf&eacute; Temps trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page in the Caf&eacute; Temps Platform, without Caf&eacute; Temps's express written consent;</li>
  <li >dilute, tarnish or otherwise harm the Caf&eacute; Temps brand in any way, including through unauthorized use of Collective Content, registering and/or using Caf&eacute; Temps or derivative terms in domain names, trade names, trademarks or other source identifiers, or registering and/or using domains names, trade names, trademarks or other source identifiers that closely imitate or are confusingly similar to Caf&eacute; Temps domains, trademarks, taglines, promotional campaigns or Collective Content;</li>
  <li >use any robots, spider, crawler, scraper or other automated means or processes to access, collect data or other content from or otherwise interact with the Caf&eacute; Temps Platform for any purpose;</li>
  <li >avoid, bypass, remove, deactivate, impair, descramble, or otherwise attempt to circumvent any technological measure implemented by Caf&eacute; Temps or any of Caf&eacute; Temps's providers or any other third party to protect the Caf&eacute; Temps Platform; attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Caf&eacute; Temps Platform;</li>
  <li >take any action that damages or adversely affects, or could damage or adversely affect the performance or proper functioning of the Caf&eacute; Temps Platform; or</li>
  <li >violate or infringe anyone else&rsquo;s rights or otherwise cause harm to anyone.</li>
  </ul>
  <p>13.2 You acknowledge that Caf&eacute; Temps has no obligation to monitor the access to or use of the Caf&eacute; Temps Platform by any Member or to review, disable access to, or edit any Member Content, but has the right to do so, including without limitation to (i) operate, secure and improve the Caf&eacute; Temps Platform (including without limitation for fraud prevention, risk assessment, investigation and customer support purposes); (ii) ensure Members&rsquo; compliance with this Agreement; (iii) comply with applicable law or the order or requirement of a court, law enforcement or other administrative agency or governmental body; (iv) respond to Member Content that it determines is harmful or objectionable; or (v) as otherwise set forth in this Agreement. Members agree to cooperate with and assist Caf&eacute; Temps in good faith, and to provide Caf&eacute; Temps with such information and take such actions as may be reasonably requested by Caf&eacute; Temps with respect to any investigation undertaken by Caf&eacute; Temps or a representative of Caf&eacute; Temps regarding the use or abuse of the Caf&eacute; Temps Platform.</p>
  <p>13.3 If you feel that any Member you interact with, whether online or in person, is acting or has acted inappropriately, including but not limited to anyone who (i) engages in offensive, violent or sexually inappropriate behavior, (ii) you suspect of stealing from you, or (iii) engages in any other disturbing conduct, you should immediately report such person to the appropriate authorities and then to Caf&eacute; Temps by contacting us with your police station and report number (if available); provided that your report will not obligate us to take any action beyond that required by law (if any) or cause us to incur any liability to you.</p>
  <h3>14. Term and Termination, Suspension and other Measures</h3>
  <p>14.1 This Agreement shall be effective for a 30-day term, at the end of which it will automatically and continuously renew for subsequent 30-day terms until such time when you or Caf&eacute; Temps terminate the Agreement in accordance with this provision.&nbsp;</p>
  <p>14.2 You may terminate this Agreement at any time by sending us an email to admin@cafetemps.com.&nbsp;</p>
  <p>14.3 Without limiting our rights specified below, Caf&eacute; Temps may terminate this Agreement for convenience at any time by giving you thirty (30) days' notice via email to your registered email address.</p>
  <p>14.4 Caf&eacute; Temps may immediately, without notice terminate this Agreement if (i) you have materially breached your obligations under this Agreement or any of our policies or standards, (ii) you have violated applicable laws, regulations or third party rights, or (iii) Caf&eacute; Temps believes in good faith that such action is reasonably necessary to protect the personal safety or property of Caf&eacute; Temps, its Members, or third parties (for example in the case of fraudulent behavior of a Member).</p>
  <p>14.5 In addition, Caf&eacute; Temps may take any of the following measures (i) to comply with applicable law, or the order or request of a court, law enforcement or other administrative agency or governmental body, or if (ii) you have breached these Terms our Policies or Standards, applicable laws, regulations, or third party rights, (iii) you have provided inaccurate, fraudulent, outdated or incomplete information during the Caf&eacute; Temps Account registration, Listing process or thereafter, (iv) you and/or your Listings at any time fail to meet any applicable quality or eligibility criteria, (v) you have repeatedly received poor Ratings or Reviews or Caf&eacute; Temps otherwise becomes aware of or has received complaints about your performance or conduct, (vi) you have repeatedly cancelled confirmed bookings or failed to respond to booking requests without a valid reason, or (vii) Caf&eacute; Temps believes in good faith that such action is reasonably necessary to protect the personal safety or property of Caf&eacute; Temps, its Members, or third parties, or to prevent fraud or other illegal activity:</p>
  <ul>
  <li >refuse to surface, delete or delay any Listings, Ratings, Reviews, or other Member Content; cancel any pending or confirmed bookings on the platform (note, since Caf&eacute; Temps is not a party to any booking contract between members, a cancelation on the platform will not affect the status of any contract between members); limit your access to or use of the Caf&eacute; Temps Platform; temporarily or permanently revoke any special status associated with your Caf&eacute; Temps Account; or temporarily or in case of severe or repeated offenses permanently suspend your Caf&eacute; Temps Account. In case of non-material breaches and where appropriate, you will be given notice of any intended measure by Caf&eacute; Temps and an opportunity to resolve the issue to Caf&eacute; Temps's reasonable satisfaction.</li>
  </ul>
  <p>14.6 When this Agreement has been terminated, you are not entitled to a restoration of your Caf&eacute; Temps Account or any of your Member Content. If your access to or use of the Caf&eacute; Temps Platform has been limited or your Caf&eacute; Temps Account has been suspended or this Agreement has been terminated by us, you may not register a new Caf&eacute; Temps Account or access and use the Caf&eacute; Temps Platform through an Caf&eacute; Temps Account of another Member.</p>
  <h3>15. Disclaimers</h3>
  <p>IF YOU CHOOSE TO USE THE Caf&eacute; Temps PLATFORM OR COLLECTIVE CONTENT, YOU DO SO VOLUNTARILY AND AT YOUR SOLE RISK. THE Caf&eacute; Temps PLATFORM AND COLLECTIVE CONTENT IS PROVIDED &ldquo;AS IS&rdquo;, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. Caf&eacute; Temps EXPRESSLY DISCLAIMS ALL WARRANTIES, REPRESENTATIONS, AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARISING FROM USE OF THE Caf&eacute; Temps PLATFORM AND COLLECTIVE CONTENT. Caf&eacute; Temps MAKES NO WARRANTY, REPRESENTATION OR CONDITION THAT YOUR USE OF THE Caf&eacute; Temps PLATFORM WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE.</p>
  <p>You agree that you have had whatever opportunity you deem necessary to investigate the Caf&eacute; Temps Services, laws, rules, or regulations that may be applicable to your Listings and/or Studio Services you are receiving and that you are not relying upon any statement of law or fact made by Caf&eacute; Temps relating to a Listing.</p>
  <p>YOU AGREE THAT SOME SERVICES MAY CARRY INHERENT RISK, AND BY PARTICIPATING IN THOSE SERVICES, YOU CHOOSE TO ASSUME THOSE RISKS VOLUNTARILY. FOR EXAMPLE, SOME SERVICES MAY CARRY RISK OF ILLNESS, BODILY INJURY, DISABILITY, OR DEATH, AND YOU FREELY AND WILLFULLY ASSUME THOSE RISKS BY CHOOSING TO PARTICIPATE IN THOSE SERVICES. YOU ASSUME FULL RESPONSIBILITY FOR THE CHOICES YOU MAKE BEFORE, DURING AND AFTER YOUR PARTICIPATION IN A SERVICE.</p>
  <p>NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM Caf&eacute; Temps OR THROUGH THE Caf&eacute; Temps PLATFORM WILL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</p>
  <p>YOU ACKNOWLEDGE AND AGREE THAT Caf&eacute; Temps IS NOT LIABLE, AND YOU AGREE NOT TO SEEK TO HOLD CAFE TEMPS LIABLE, FOR THE CONDUCT OF THIRD PARTIES, INCLUDING OPERATORS OF EXTERNAL SITES, AND THAT THE RISK OF INJURY FROM SUCH THIRD PARTIES RESTS ENTIRELY WITH YOU. CAFE TEMPS MAKES NO WARRANTY THAT THE GOODS AND SERVICES PROVIDED BY THIRD PARTIES WILL MEET YOUR REQUIREMENTS OR BE AVAILABLE ON AN UNINTERRUPTED, SECURE, OR ERROR-FREE BASIS. CAFE TEMPS MAKES NO WARRANTY REGARDING THE QUALITY OF ANY SUCH GOODS OR SERVICES, OR THE ACCURACY, TIMELINESS, TRUTHFULNESS, COMPLETENESS OR RELIABILITY OF ANY MEMBER CONTENT OBTAINED THROUGH THE Caf&eacute; Temps PLATFORM.</p>
  <p>The foregoing disclaimers apply to the maximum extent permitted by law. You may have other statutory rights. However, the duration of statutorily required warranties, if any, shall be limited to the maximum extent permitted by law.</p>
  <h3>16. Liability</h3>
  <p>16.1 Unless you reside in the EU, you acknowledge and agree that, to the maximum extent permitted by law, the entire risk arising out of your access to and use of the Caf&eacute; Temps Platform and Collective Content, your publishing or booking of any Listing via the Caf&eacute; Temps Platform, your stay at any restaurant, or any other interaction you have with other Members whether in person or online remains with you. NEITHER CAFE TEMPS NOR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE CAFE TEMPS PLATFORM OR COLLECTIVE CONTENT WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, LOSS OF DATA OR LOSS OF GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR THE COST OF SUBSTITUTE PRODUCTS OR SERVICES, OR FOR ANY DAMAGES FOR PERSONAL OR BODILY INJURY OR EMOTIONAL DISTRESS ARISING OUT OF OR IN CONNECTION WITH (I) THIS AGREEMENT, (II) FROM THE USE OF OR INABILITY TO USE THE Caf&eacute; Temps PLATFORM OR COLLECTIVE CONTENT, (III) FROM ANY COMMUNICATIONS, INTERACTIONS OR MEETINGS WITH OTHER MEMBERS OR OTHER PERSONS WITH WHOM YOU COMMUNICATE, INTERACT OR MEET WITH AS A RESULT OF YOUR USE OF THE Caf&eacute; Temps PLATFORM, OR (IV) FROM YOUR PUBLISHING OR BOOKING OF A LISTING, INCLUDING THE PROVISION OR USE OF A LISTING&rsquo;S STUDIO SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT Caf&eacute; Temps HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. IN NO EVENT WILL CAFE TEMPS&rsquo;S AGGREGATE LIABILITY ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT AND YOUR USE OF THE CAFE TEMPS PLATFORM INCLUDING, BUT NOT LIMITED TO, FROM YOUR PUBLISHING OR BOOKING OF ANY LISTINGS VIA THE CAFE TEMPS PLATFORM, OR FROM THE USE OF OR INABILITY TO USE THE CAFE TEMPS PLATFORM OR COLLECTIVE CONTENT AND IN CONNECTION WITH ANY WORKER, OR INTERACTIONS WITH ANY OTHER MEMBERS, EXCEED ONE HUNDRED U.S. DOLLARS (US$100). THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN CAFE TEMPS AND YOU. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IF YOU RESIDE OUTSIDE OF THE U.S., THIS DOES NOT AFFECT CAFE TEMPS&rsquo;S LIABILITY FOR DEATH OR PERSONAL INJURY ARISING FROM ITS NEGLIGENCE, NOR FOR FRAUDULENT MISREPRESENTATION, MISREPRESENTATION AS TO A FUNDAMENTAL MATTER OR ANY OTHER LIABILITY WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
  <p>16.2 IF YOU RESIDE IN THE EU, CAFE TEMPS IS LIABLE UNDER STATUTORY PROVISIONS FOR INTENT AND GROSS NEGLIGENCE BY US, OUR LEGAL REPRESENTATIVES, DIRECTORS, OR OTHER VICARIOUS AGENTS. THE SAME APPLIES TO THE ASSUMPTION OF GUARANTEES OR ANY OTHER STRICT LIABILITY, OR IN CASE OF A CULPABLE INJURY TO LIFE, LIMB, OR HEALTH. Caf&eacute; Temps IS LIABLE FOR ANY NEGLIGENT BREACHES OF ESSENTIAL CONTRACTUAL OBLIGATIONS BY US, OUR LEGAL REPRESENTATIVES, DIRECTORS, OR OTHER VICARIOUS AGENTS. ESSENTIAL CONTRACTUAL OBLIGATIONS ARE SUCH DUTIES OF CAFE TEMPS IN WHOSE PROPER FULFILMENT YOU REGULARLY TRUST AND MUST TRUST FOR THE PROPER EXECUTION OF THE CONTRACT BUT THE AMOUNT SHALL BE LIMITED TO THE TYPICALLY OCCURRING FORESEEABLE DAMAGE. ANY ADDITIONAL LIABILITY OF Caf&eacute; Temps IS EXCLUDED.</p>
  <h3>17. Indemnification</h3>
  <p>You agree to release, defend (at Caf&eacute; Temps&rsquo;s option), indemnify, and hold Caf&eacute; Temps and its affiliates and subsidiaries, and their officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with (i) your breach of this Agreement or any of our policies or standards, (ii) your improper use of the Caf&eacute; Temps Platform or any Caf&eacute; Temps Services, (iii) your interaction with any Member, stay at a Restaurant, participation in services as a Worker, including without limitation any injuries, losses or damages (whether compensatory, direct, incidental, consequential or otherwise) of any kind arising in connection with or as a result of such interaction, stay, participation or use, or (iv) your breach of any laws, regulations or third party rights. Caf&eacute; Temps reserves the right, at its own cost, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with Caf&eacute; Temps in asserting any available defenses. This provision does not require you to indemnify Caf&eacute; Temps for any unconscionable commercial practice by such party or for such party&rsquo;s fraud, deception, false promise, misrepresentation or concealment, or suppression or omission of any material fact in connection with the Site or any Caf&eacute; Temps Services provided hereunder. You agree that the provisions in this section will survive any termination of your Caf&eacute; Temps Account, this Agreement and/or your access to Caf&eacute; Temps Platform.</p>
  <h3>18. Dispute Resolution and Arbitration Agreement</h3>
  <p>18.1 This Dispute Resolution and Arbitration Agreement shall apply if you (i) reside in the United States; or (ii) do not reside in the United States, but bring any claim against Caf&eacute; Temps in the United States (to the extent not in conflict with Section 20).</p>
  <p>18.2 Overview of Dispute Resolution Process. Caf&eacute; Temps is committed to participating in a consumer-friendly dispute resolution process. To that end, these Terms provide for a two-part process for individuals to whom Section 18.1 applies: (1) an informal negotiation directly with Caf&eacute; Temps&rsquo;s customer service team, and (2) a binding arbitration administered by the American Arbitration Association (&ldquo;AAA&rdquo;) using its specially designed Consumer Arbitration Rules (as modified by this Section 18). Specifically, the process provides:</p>
  <p>Claims can be filed with AAA online (www.adr.org); Arbitrators must be neutral and no party may unilaterally select an arbitrator; Arbitrators must disclose any bias, interest in the result of the arbitration, or relationship with any party; Parties retain the right to seek relief in small claims court for certain claims, at their option; The initial filing fee for the consumer is capped at $200; The consumer gets to elect the hearing location and can elect to participate live, by phone, video conference, or, for claims under $25,000, by the submission of documents; The arbitrator can grant any remedy that the parties could have received in court to resolve the party&rsquo;s individual claim.</p>
  <p>18.3 Pre-Arbitration Dispute Resolution and Notification. Prior to initiating an arbitration, you and Caf&eacute; Temps each agree to notify the other party of the dispute and attempt to negotiate an informal resolution to it first. We will contact you at the email address you have provided to us; you can contact Caf&eacute; Temps&rsquo;s customer service team by emailing us at admin@cafetemps.com. If after a good faith effort to negotiate one of us feels the dispute has not and cannot be resolved informally, the party intending to pursue arbitration agrees to notify the other party via email prior to initiating the arbitration. In order to initiate arbitration, a claim must be filed with the AAA and the written Demand for Arbitration (available at www.adr.org) provided to the other party, as specified in the AAA Rules.</p>
  <p>18.4 Agreement to Arbitrate. You and Caf&eacute; Temps mutually agree that any dispute, claim or controversy arising out of or relating to these Terms or the breach, termination, enforcement or interpretation thereof, or to the use of the Caf&eacute; Temps Platform, the Studio Services, or the Collective Content (collectively, &ldquo;Disputes&rdquo;) will be settled by binding arbitration (the &ldquo;Arbitration Agreement&rdquo;). If there is a dispute about whether this Arbitration Agreement can be enforced or applies to our Dispute, you and Caf&eacute; Temps agree that the arbitrator will decide that issue.</p>
  <p>18.5 Exceptions to Arbitration Agreement. You and Caf&eacute; Temps each agree that the following claims are exceptions to the Arbitration Agreement and will be brought in a judicial proceeding in a court of competent jurisdiction: (i) Any claim related to actual or threatened infringement, misappropriation or violation of a party&rsquo;s copyrights, trademarks, trade secrets, patents, or other intellectual property rights; (ii) Any claim seeking emergency injunctive relief based on exigent circumstances (e.g., imminent danger or commission of a crime, hacking, cyber-attack).</p>
  <p>18.6 Arbitration Rules and Governing Law. This Arbitration Agreement evidences a transaction in interstate commerce and thus the Federal Arbitration Act governs the interpretation and enforcement of this provision. The arbitration will be administered by AAA in accordance with the Consumer Arbitration Rules (the &ldquo;AAA Rules&ldquo;) then in effect, except as modified here. The AAA Rules are available at www.adr.org or by calling the AAA at 1&ndash;800&ndash;778&ndash;7879.</p>
  <p>18.7 Modification to AAA Rules - Arbitration Hearing/Location. In order to make the arbitration most convenient to you, Caf&eacute; Temps agrees that any required arbitration hearing may be conducted, at Caf&eacute; Temps option, (a) in the county where you reside; (b) in Hennepin County; (c) in any other location to which you and Caf&eacute; Temps both agree; (d) via phone or video conference; or (e) for any claim or counterclaim under $25,000, by solely the submission of documents to the arbitrator.</p>
  <p>18.8 Modification of AAA Rules - Attorney&rsquo;s Fees and Costs. You may be entitled to seek an award of attorney fees and expenses if you prevail in arbitration, to the extent provided under applicable law and the AAA rules. Unless the arbitrator determines that your claim was frivolous or filed for the purpose of harassment, Caf&eacute; Temps agrees it will not seek, and hereby waives all rights it may have under applicable law or the AAA rules, to recover attorneys&rsquo; fees and expenses if it prevails in arbitration.</p>
  <p>18.9 Arbitrator&rsquo;s Decision. The arbitrator&rsquo;s decision will include the essential findings and conclusions upon which the arbitrator based the award. Judgment on the arbitration award may be entered in any court with proper jurisdiction. The arbitrator may award declaratory or injunctive relief only on an individual basis and only to the extent necessary to provide relief warranted by the claimant&rsquo;s individual claim.</p>
  <p>18.10 Jury Trial Waiver. You and Caf&eacute; Temps acknowledge and agree that we are each waiving the right to a trial by jury as to all arbitrable Disputes.</p>
  <p>18.11 No Class Actions or Representative Proceedings. You and Caf&eacute; Temps acknowledge and agree that we are each waiving the right to participate as a plaintiff or class member in any purported class action lawsuit, class-wide arbitration, private attorney-general action, or any other representative proceeding as to all Disputes. Further, unless you and Caf&eacute; Temps both otherwise agree in writing, the arbitrator may not consolidate more than one party&rsquo;s claims and may not otherwise preside over any form of any class or representative proceeding. If this paragraph is held unenforceable with respect to any Dispute, then the entirety of the Arbitration Agreement will be deemed void with respect to such Dispute.</p>
  <p>18.12 Severability. Except as provided in Section 18.11, in the event that any portion of this Arbitration Agreement is deemed illegal or unenforceable, such provision shall be severed and the remainder of the Arbitration Agreement shall be given full force and effect.</p>
  <p>18.13 Changes. Notwithstanding the provisions of Section 3 (&ldquo;Modification of these Terms&rdquo;), if Caf&eacute; Temps changes this Section 18 (&ldquo;Dispute Resolution and Arbitration Agreement&rdquo;) after the date you last accepted these Terms (or accepted any subsequent changes to these Terms), you may reject any such change by sending us written notice (including by email) within thirty (30) days of the date such change became effective, as indicated in the &ldquo;Last Updated&rdquo; date above or in the date of Caf&eacute; Temps notifying you of such change. By rejecting any change, you are agreeing that you will arbitrate any Dispute between you and Caf&eacute; Temps in accordance with the provisions of the &ldquo;Dispute Resolution and Arbitration Agreement&rdquo; section as of the date you last accepted these Terms (or accepted any subsequent changes to these Terms).</p>
  <p>18.14 Survival. Except as provided in Section 18.12, this Section 18 will survive any termination of this Agreement and will continue to apply even if you stop using the Caf&eacute; Temps Platform or terminate your Caf&eacute; Temps Account.</p>
  <h3>19. Feedback</h3>
  <p>We welcome and encourage you to provide feedback, comments and suggestions for improvements to the Caf&eacute; Temps Platform (&ldquo;Feedback&ldquo;). You may submit Feedback by emailing us at admin@cafetemps.com. Any Feedback you submit to us will be considered non-confidential and non-proprietary to you. By submitting Feedback to us, you grant us a non-exclusive, worldwide, royalty-free, irrevocable, sub-licensable, perpetual license to use and publish those ideas and materials for any purpose, without compensation to you.</p>
  <h3>20. Applicable Law and Jurisdiction</h3>
  <p>20.1 If you reside in the United States, these Terms will be interpreted in accordance with the laws of the State of Minnesota and the United States of America, without regard to conflict-of-law provisions. Judicial proceedings (other than small claims actions) that are excluded from the Arbitration Agreement in Section 18 must be brought in state or federal court in Minneapolis, Minnesota, unless we both agree to some other location. You and we both consent to venue and personal jurisdiction in Minneapolis, Minnesota.</p>
  <p>20.2 If you reside in China these Terms will be interpreted in accordance with the laws of China (&ldquo;China Laws&rdquo;). Any dispute arising from or in connection with this Agreement shall be submitted to the China International Economic and Trade Arbitration Commission (CIETAC) for arbitration in Beijing which shall be conducted in accordance with CIETAC&rsquo;s arbitration rules in effect at the time of applying for arbitration, provided that this section shall not be construed to limit any rights which Caf&eacute; Temps may have to apply to any court of competent jurisdiction for an order requiring you to perform or be prohibited from performing certain acts and other provisional relief permitted under China Laws or any other laws that may apply to you. The arbitration proceedings shall be conducted in English. The arbitral award rendered is final and binding upon both parties.</p>
  <p>20.3 If you reside outside of the United States and China, these Terms will be interpreted in accordance with Irish law. The application of the United Nations Convention on Contracts for the International Sale of Goods (CISG) is excluded. The choice of law does not impact your rights as a consumer according to the consumer protection regulations of your country of residence. If you are acting as a consumer, you agree to submit to the non-exclusive jurisdiction of the Irish courts. Judicial proceedings that you are able to bring against us arising from or in connection with these Terms may only be brought in a court located in Ireland or a court with jurisdiction in your place of residence. If Caf&eacute; Temps wishes to enforce any of its rights against you as a consumer, we may do so only in the courts of the jurisdiction in which you are a resident. If you are acting as a business, you agree to submit to the exclusive jurisdiction of the Irish courts.</p>
  <h3>21. General Provisions</h3>
  <p>21.1 Except as they may be supplemented by additional terms and conditions, policies, guidelines or standards, these Terms constitute the entire Agreement between Caf&eacute; Temps and you pertaining to the subject matter hereof, and supersede any and all prior oral or written understandings or agreements between Caf&eacute; Temps and you in relation to the access to and use of the Caf&eacute; Temps Platform.</p>
  <p>21.2 No joint venture, partnership, employment, or agency relationship exists between you and Caf&eacute; Temps as a result of this Agreement or your use of the Caf&eacute; Temps Platform.</p>
  <p>21.3 This Agreement does not and is not intended to confer any rights or remedies upon any person other than the parties.</p>
  <p>21.4 If any provision of this Agreement is held to be invalid or unenforceable, such provision will be struck and will not affect the validity and enforceability of the remaining provisions.</p>
  <p>21.5 Caf&eacute; Temps&rsquo;s failure to enforce any right or provision in this Agreement will not constitute a waiver of such right or provision unless acknowledged and agreed to by us in writing. Except as expressly set forth in this Agreement, the exercise by either party of any of its remedies under this Agreement will be without prejudice to its other remedies under this Agreement or otherwise permitted under law.</p>
  <p>21.6 You may not assign, transfer or delegate this Agreement and your rights and obligations hereunder without Caf&eacute; Temps's prior written consent. Caf&eacute; Temps may without restriction assign, transfer or delegate this Agreement and any rights and obligations hereunder, at its sole discretion. Your right to terminate this Agreement at any time remains unaffected.</p>
  <p>21.7 Unless specified otherwise, any notices or other communications to Members permitted or required under this Agreement, will be in writing and given by Caf&eacute; Temps via email, Caf&eacute; Temps Platform notification, or messaging service (including SMS and WeChat). For notices made to Members residing outside of Germany, the date of receipt will be deemed the date on which Caf&eacute; Temps transmits the notice.</p>
  <p>21.8 If you have any questions about this Agreement please email us at admin@cafetemps.com.</p>
  <h3><br /><br /></h3>
    </div>
  );
};

TermsOfService.defaultProps = {
  rootClassName: null,
  className: null,
};

const { string } = PropTypes;

TermsOfService.propTypes = {
  rootClassName: string,
  className: string,
};

export default TermsOfService;
